### ISSUE TITLE
How to attach logger ?

### ISSUE THREAD

**Issue by Ilkhom-S** [davidbwire/instant-ussd-app#2]
Hello, 
I'm trying to make test application. Can you show how to attach logger to it

**Comment by davidbwire** [comment]
- Install a logger of your choice via composer
- Edit the [`service_manager`](https://github.com/davidbwire/instant-ussd-app/blob/4fc93584f7830708bd9a99a166007a317862b668/config/iussd.config.php#L26) section of `iussd.config.php` file and register your preferred logger

```
"service_manager" => [
            "factories" => [
                'logger' => function ($sm) {
                    // see - https://docs.zendframework.com/zend-log/
                    $logger = new \Zend\Log\Logger();
                    $writer = new \Zend\Log\Writer\Stream('./logfile.txt');
                    $logger->addWriter($writer);
                    return $logger;
                },
                "dbAdapter" => Zend\Db\Adapter\AdapterServiceFactory::class,
            ]
        ]
```
- Access the logger from [USSD listener](https://github.com/davidbwire/instant-ussd-app/blob/4fc93584f7830708bd9a99a166007a317862b668/Listeners/HomeInstantUssd.php#L16) by retrieving it from the service_manager

```
$serviceLocator = $this->ussdEvent->getServiceLocator();
        $logger = $serviceLocator->get('logger');
        if ($logger instanceof \Zend\Log\Logger) {
            $logger->log(\Zend\Log\Logger::INFO, "My message");
        } else {
            throw new \Exception('Logger not registered with the service_manager');
        }
```

**Comment by Ilkhom-S** [comment]
Thanks, 
Also do you any mocker or tester. to send ussd from web to listener. Our operator sending only xml and I have to return XML.

**Comment by davidbwire** [comment]
I normally use postman for local simulations. The current project doesn't currently support XML consumption and rendering but it should be possible to build a custom parser and renderer.

**Comment by Ilkhom-S** [comment]
Ok, thanks
