### ISSUE TITLE
Column 'session_id' cannot be null

### ISSUE THREAD

**Issue by dpchami** [davidbwire/instant-ussd-app#4]
Hello,

Please help me to resolve this, I tried to run the application after set up the database and he configuration file. Unfortunately when run it I get the above error. Is there any setting I have to make before testing the application.

Am running on php 7.2 in windows environment

**Comment by davidbwire** [comment]
Hi. Check that the POST data your are sending contains a `sessionId` key. The POST data should be something like this `$_POST      = array(
          'text' => '1',
          'sessionId' => 'xxxxxxxxxxx',
          'phoneNumber' => 'xxxxx',
          'serviceCode' => '*XXX#',
          );`

**Comment by dpchami** [comment]
Thanks 
Solved.
