### ISSUE TITLE
Custom menu leads to error

### ISSUE THREAD

**Issue by dpchami** [davidbwire/instant-ussd-app#5]
Hello,

I keep getting this error , I have customizing the app 

![image](https://user-images.githubusercontent.com/19475836/47141806-29b8be00-d2ca-11e8-9d8b-76c470eb8dd9.png)

I have observed the different in dump result from your app to mine, What is the problem is EventManager listener in showhomepage() does not return instance of Response

This is the response from event manager listeneresult

![image](https://user-images.githubusercontent.com/19475836/47140471-f3c60a80-d2c6-11e8-8f44-9717d5dcd3b2.png)

This is my menus option
![image](https://user-images.githubusercontent.com/19475836/47141861-481eb980-d2ca-11e8-8c78-74506b7e7712.png)

**Comment by davidbwire** [comment]
Have you replaced all instances of `home_instant_ussd`  with `home_family_ussd` on [this file](https://github.com/davidbwire/instant-ussd-app/blob/4fc93584f7830708bd9a99a166007a317862b668/UssdController.php#L57) (Alternavely, you may rename `home_family_ussd` on your config file to `home_instant_ussd`)?

**Comment by dpchami** [comment]
When I changed the name works fine?

I have created custom controller, eventManager, validator, and config files to suit my application. and  changing all the menus instance of **iussd** . The challenge now is some of the menu-option keeps prompting error that not iniatialized in UssdLoopMapper.

Is there any changes(other than the one I mentioned above) will I needed to work on so as to make it up ?
